//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Factura
    {
        public int CodFactura { get; set; }
        public string Numero { get; set; }
        public int CodCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Comentarios { get; set; }
        public int Estatus { get; set; }
        public decimal MontoTotal { get; set; }
        public Nullable<decimal> MontoDescuento { get; set; }
        public Nullable<decimal> MontoDevuelto { get; set; }
    
        public virtual TBL_Cliente TBL_Cliente { get; set; }
        public virtual TBL_Factura_D TBL_Factura_D { get; set; }
    }
}
