//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ProductoExistencia
    {
        public int CodProductoExistencia { get; set; }
        public Nullable<int> CodProducto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
    
        public virtual TBL_Producto TBL_Producto { get; set; }
    }
}
