//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionSysDLL.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Producto()
        {
            this.TBL_Factura_D = new HashSet<TBL_Factura_D>();
            this.TBL_InventarioMovimiento_D = new HashSet<TBL_InventarioMovimiento_D>();
            this.TBL_Pedido_D = new HashSet<TBL_Pedido_D>();
            this.TBL_ProductoExistencia = new HashSet<TBL_ProductoExistencia>();
        }
    
        public int CodProducto { get; set; }
        public string Referencia { get; set; }
        public string Descripcion { get; set; }
        public int Estatus { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<System.DateTime> FecInclusion { get; set; }
        public Nullable<System.DateTime> FecModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Factura_D> TBL_Factura_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_InventarioMovimiento_D> TBL_InventarioMovimiento_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Pedido_D> TBL_Pedido_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ProductoExistencia> TBL_ProductoExistencia { get; set; }
    }
}
