//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionSysDLL.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Cliente()
        {
            this.TBL_CuentasPorCobrar = new HashSet<TBL_CuentasPorCobrar>();
            this.TBL_Factura = new HashSet<TBL_Factura>();
            this.TBL_Pedido = new HashSet<TBL_Pedido>();
        }
    
        public int CodCliente { get; set; }
        public string NumIdentif { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Descripcion { get; set; }
        public int Estatus { get; set; }
        public string Direccion { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CuentasPorCobrar> TBL_CuentasPorCobrar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Factura> TBL_Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Pedido> TBL_Pedido { get; set; }
    }
}
