//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionSysDLL.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_InventarioMovimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_InventarioMovimiento()
        {
            this.TBL_InventarioMovimiento_D = new HashSet<TBL_InventarioMovimiento_D>();
        }
    
        public int CodMovimiento { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Comentarios { get; set; }
        public int Estatus { get; set; }
        public decimal MontoTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_InventarioMovimiento_D> TBL_InventarioMovimiento_D { get; set; }
    }
}
